### ISSUE TITLE
Error compiling GVSoC

### ISSUE THREAD

**Issue by Fred-03** [pulp-platform/pulp-sdk#134]
I have been following the getting started instructions and continue to get an error when compiling GVSoC.

The command run is:
$ make build

The error message is:
cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo \
	-DCMAKE_INSTALL_PREFIX=/home/pulp/pulp-sdk/install/workstation \
	-DGVSOC_MODULES="/home/pulp/pulp-sdk/tools/gvsoc/common;/home/pulp/pulp-sdk/tools/gvsoc/pulp" \
	-DGVSOC_TARGETS=pulp-open
CMake Error: The source directory "/home/pulp/pulp-sdk/build" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Makefile:26: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by Felix-ziteng** [comment]
You need to use "git submodule update --init --recursive" to update the code to newest version.

**Comment by Wen-Sheng** [comment]
HI~ @Felix-ziteng 
I executed the command (git submodule update --init --recursive), but still encounter this problem...
what should i do ?

**Comment by Felix-ziteng** [comment]
@Wen-Sheng If you can't figure the problem out, maybe you can simply use the VM image(CentOS) on their website,
https://pulp-platform.org/pulp_training.html
