### ISSUE TITLE
Build looks in the wrong directory for the compiler

### ISSUE THREAD

**Issue by lstrz** [pulp-platform/pulp-sdk#14]
After sourcing configs and running `make all`, in the end I get a message

sdk:pulp-rt:build (user_config_file=/home/lstrz/Desktop/pulp-sdk/configs/json/pulpissimo-zeroriscy.json): make build install
make[1]: Entering directory '/home/lstrz/Desktop/pulp-sdk/runtime/pulp-rt'
/home/lstrz/Desktop/pulp-sdk/pkg/pulp_riscv_gcc/1.0.4/bin/riscv32-unknown-elf-gcc  -march=rv32imcxpulpslim -DRV_ISA_RV32=1 -D__riscv__ -Os -g -fno-jump-tables -fno-tree-loop-distribute-patterns -Werror  -Wextra -Wall -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wundef -fdata-sections -ffunction-sections -I/home/lstrz/Desktop/pulp-sdk/pkg/sdk/dev/install/include/io -I/home/lstrz/Desktop/pulp-sdk/pkg/sdk/dev/install/include -include /home/lstrz/Desktop/pulp-sdk/runtime/pulp-rt/build/user_config_file..home.lstrz.Desktop.pulp-sdk.configs.json.pulpissimo-zeroriscy.json/fc_config.h    -MMD -MP -c kernel/init.c -o /home/lstrz/Desktop/pulp-sdk/runtime/pulp-rt/build/user_config_file..home.lstrz.Desktop.pulp-sdk.configs.json.pulpissimo-zeroriscy.json/rt/fc/kernel/init.o
**make[1]: /home/lstrz/Desktop/pulp-sdk/pkg/pulp_riscv_gcc/1.0.4/bin/riscv32-unknown-elf-gcc: Command not found**
/home/lstrz/Desktop/pulp-sdk/runtime/pulp-rt/build/user_config_file..home.lstrz.Desktop.pulp-sdk.configs.json.pulpissimo-zeroriscy.json/__rules.mk:55: recipe for target '/home/lstrz/Desktop/pulp-sdk/runtime/pulp-rt/build/user_config_file..home.lstrz.Desktop.pulp-sdk.configs.json.pulpissimo-zeroriscy.json/rt/fc/kernel/init.o' failed
make[1]: *** [/home/lstrz/Desktop/pulp-sdk/runtime/pulp-rt/build/user_config_file..home.lstrz.Desktop.pulp-sdk.configs.json.pulpissimo-zeroriscy.json/rt/fc/kernel/init.o] Error 127
make[1]: Leaving directory '/home/lstrz/Desktop/pulp-sdk/runtime/pulp-rt'
Reached EOF with exit status 2
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 255

As instructed in the readme, I've set the correct environment variable to the toolchain, which is very different from the location `/home/lstrz/Desktop/pulp-sdk/pkg/pulp_riscv_gcc/1.0.4/bin/` that the build script is looking at. I could not find an environment variable or a line in the scripts which is responsible for this location.

What should I do different? My `.../pulp-sdk/pkg` directory does not contain a `pulp_riscv_gcc` dir.

The simplest solution seems to be to link all the tools in the "not found" location, but that seems incredibly hacky.

**Comment by haugoug** [comment]
Have you defined this env var:
export PULP_RISCV_GCC_TOOLCHAIN=<path to your compiler>

**Comment by lstrz** [comment]
Yes.

**Comment by haugoug** [comment]
I didn't manage to reproduce your issue and noone reported something similar. Could you try again from scratch and give me the exact list of commands that you execute ?

**Comment by haugoug** [comment]
Should we close the tracker ?

**Comment by lstrz** [comment]
Not yet, please. I was multiplexing some work and will return to this shortly.

**Comment by josipknezovic** [comment]
I just had the similar issue: you should set the PULP_RISCV_GCC_TOOLCHAIN to the root folder you specified as --prefix while building pulp-riscv-gnu-toolchain project. For example, if you specified to build and place it into /opt/riscv - that should be set to PULP_RISCV_GCC_TOOLCHAIN. In addition, update your path to include /opt/riscv/bin.

**Comment by lstrz** [comment]
I have returned to this and the issue no longer exists with @josipknezovic's input. Closing!
