### ISSUE TITLE
SDK build error with pulp-rt-exemple

### ISSUE THREAD

**Issue by lfernand4** [pulp-platform/pulp-sdk#15]
Hi, Pulp team : 
I have build the SDK and I want to test it with the hello test. 
I think i have all the correct path and source : 
![image](https://user-images.githubusercontent.com/36438648/39426188-26142e46-4c7f-11e8-833d-3786ab85c365.png)
but I have the following error : 
![image](https://user-images.githubusercontent.com/36438648/39426214-3bcbeae4-4c7f-11e8-8c05-34e51433c626.png)

Any idea/suggestion?

Regards,
Léo

**Comment by haugoug** [comment]
It seems your design installation is wrong. Could you check if $VSIM_PATH really contains modelsim.ini ?

**Comment by haugoug** [comment]
Did you move the VSIM_PATH folder after you built it ? There are some hard-coded paths inside modelsim.ini, you can check if they are right.

**Comment by lfernand4** [comment]
No

**Comment by haugoug** [comment]
Can you recompile the whole design and post the full log ?

**Comment by lfernand4** [comment]
I am new in this area. Thanks for your help. 
You mean to execute : pulp-rt-examples/hello/make clean all run ?

**Comment by haugoug** [comment]
You can go to your directory $VSIM_PATH and execute:
make all &> log
Then you can post the log file

**Comment by lfernand4** [comment]
[log.log](https://github.com/pulp-platform/pulp-sdk/files/1960556/log.log)

**Comment by haugoug** [comment]
Ok the issue is actually that you get some errors when compiling the design.
This is strange why you get so many errors. Did you modify anything in the design ?
If not, could you retry by first updating to the latest design ?
To do it you can go to pulpissimo folder and execute:
git checkout master
git pull
./update-ips

**Comment by lfernand4** [comment]
I have modify nothing. I have update the design and I have the same issue.

**Comment by haugoug** [comment]
Can you remove the pulpissimo/ips folder, execute again ./update-ips &> log and send me the log ?

**Comment by lfernand4** [comment]
[log.log](https://github.com/pulp-platform/pulp-sdk/files/1960787/log.log)
Only 'pulp_soc' is cloning

**Comment by FrancescoConti** [comment]
Hi @lfernand4 , the `ipstools` are using the `curl` utility in background to download the list of IPs required by `pulp_soc` from GitHub. Can you manually check that the command
```
curl https://raw.githubusercontent.com/pulp-platform/pulp_soc/master/ips_list.yml
```
returns a list of IPs and tags?
Also, for debugging I would require the version of python,
```
python3 --version
```
and which OS and version you are using.

As a temporary workaround, you can also:
1. copy the entire content downloaded from the `curl` command above on the top part of `ips_list.yml`
2. edit `update-ips.py` by setting `build_deps_tree=False` and `resolve_deps_conflicts=False` (lines 16-17).
This will bypass hierarchy resolution and use a flat `ips_list.yml` file
