### ISSUE TITLE
Permission for pulp SDK

### ISSUE THREAD

**Issue by valenaUsi** [pulp-platform/pulp-sdk#2]
Hello everyone,

I am trying to download the sdk for pulpissimo using the command:
git clone git@iis-git.ee.ethz.ch:pulp-sw/pulp-sdk.git -b master

But the it asks me for the password, I have search through the document and there is any password.
I do not see any way to register to https://iis-git.ee.ethz.ch/, which i supposed is private.

So I would like to ask you how I can get the access to pulp-sdk

Thanks in advance

**Comment by FrancescoConti** [comment]
There is a typo in the README file. The correct command is `git clone git@github.com:pulp-platform/pulp-sdk.git -b master`. We will fix the README as soon as possible :)
