### ISSUE TITLE
Checkout failed

### ISSUE THREAD

**Issue by GAnto85** [pulp-platform/pulp-sdk#20]
Hi, i've got the following error. I have installed it a few times before and i never ran into this problem. Since two days ago im not able to complete the creation of the pkg/sdk/dev folder. Thank you in advance.

![image](https://user-images.githubusercontent.com/39409379/40236663-9939350a-5aae-11e8-9911-d9baac7e13d3.png)

**Comment by haugoug** [comment]
Indeed, the behavior has been changed, it is now fetching repository using ssh instead of https. You can force it to use https by defining this env var:
export PULP_GITHUB_HTTPS=1
I've fixed the documentation

**Comment by GAnto85** [comment]
I've tried that too, without success so far. I can try again tomorrow , maybe its a temporary problem.

**Comment by haugoug** [comment]
Try to download again from scratch maybe this will help

**Comment by GAnto85** [comment]
Hi i tried to download it from scratch several times since the last thursday but still running into the same issue: 
![image](https://user-images.githubusercontent.com/39409379/40432204-6eaab990-5ea9-11e8-9568-77e890f18d50.png)
Are you able to download it or is it just a problem of mine?

**Comment by haugoug** [comment]
I've restored the previous behavior, this will now use https by default, you can try again to clone from scratch this should now work

**Comment by GAnto85** [comment]
Thank you very much! It works now.
