### ISSUE TITLE
pulp-sdk build failed

### ISSUE THREAD

**Issue by bkr10** [pulp-platform/pulp-sdk#22]
Hi,

I'm building the most recent patch, a1d73765373792a741123432e02defa84dec02bd, but the build fails as below.

Steps followed to build pulp-sdk:
export PULP_RISCV_GCC_TOOLCHAIN= <set to the right build directory>
source configs/pulp.sh

Build error:
install -D PULP/pulp-sdk/platform/vp/models/build/models/utils/injector_impl.so PULP/pulp-sdk/pkg/sdk/dev/install/ws/python/utils/injector_impl.so
make[2]: *** No rule to make target 'PULP/pulp-sdk/platform/vp/models/build/models/utils/composite_impl/utils/composite_impl.o', needed by 'PULP/pulp-sdk/platform/vp/models/build/models/utils/composite_impl.so'.  Stop.
make[2]: Leaving directory 'PULP/pulp-sdk/platform/vp/models'
Makefile:9: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory 'PULP/pulp-sdk/platform/vp'
Reached EOF with exit status 2
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 255

Is the makefile broken in this latest patch? I was able to build the previous patch, 79daee01e5fc21b6d833c68e866a148e98f11f90.

Thank you!

**Comment by haugoug** [comment]
Something was pushed by mistake to master branch, this should be fixed now, can you update and try again ?

**Comment by bkr10** [comment]
Thanks for fixing the master. The build succeeds now as below.

reading sources... [100%] virtual_platform
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] virtual_platform
generating indices... genindex
writing additional pages... search
copying static files... WARNING: html_static_path entry u'/PULP/pulp-sdk/doc/top/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 3 warnings.
Build finished. The HTML pages are in _build/html.

But when I try to run the hello test program using virtual platform, it still fails. I'll post the error in issue#21 as it the same error.

Thanks!
