### ISSUE TITLE
Checkout failed - Asks password 

### ISSUE THREAD

**Issue by bkr10** [pulp-platform/pulp-sdk#23]
Hi,

I'm trying to build the most recent patch, a1d73765373792a741123432e02defa84dec02bd.

Steps followed to build pulp-sdk:
export PULP_RISCV_GCC_TOOLCHAIN= <set to the right path>
source configs/wolfe.sh
export PULP_GITHUB_HTTPS=1 (Following the answer provided in issue#20)

When I do 'make all',
git submodule update --init
Submodule 'pulp-tools' (https://github.com/pulp-platform/pulp-tools.git) registered for path 'pulp-tools'
Cloning into 'PULP/pulp-sdk/pulp-tools'...
Submodule path 'pulp-tools': checked out '4d5b7dc30e8858adb021de2f8f516492ebccd3d6'
plpbuild --p sdk checkout build --stdout

MODULE debug-bridge:debug-bridge command checkout
Cloning into 'PULP/pulp-sdk/tools/debug-bridge'...
The authenticity of host 'iis-git.ee.ethz.ch (129.132.2.24)' can't be established.
ECDSA key fingerprint is SHA256:jI6MDtrI7TVLgVlEPvDwfcNhbwW61ugYg8jo74W51Do.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'iis-git.ee.ethz.ch,129.132.2.24' (ECDSA) to the list of known hosts.
git@iis-git.ee.ethz.ch's password:

The password prompt occurs only when I 'source wolfe.sh'. But if I 'source pulp.sh', I don't encounter this issue.

Thank you!

**Comment by haugoug** [comment]
Wolfe is reserved for internal usage, why do you want to use it instead of pulp ?
