### ISSUE TITLE
Porting pthread application to pulp-sdk 

### ISSUE THREAD

**Issue by bkr10** [pulp-platform/pulp-sdk#24]
Hi,

I'm trying to port an application to run on the pulp's virtual platform. But it uses some pthread calls & to my knowledge newlib doesn't support pthreads. 

I see pulp-os implements it own thread library in pulp-sdk/runtime/pulp-rt/kernel/thread.c.

It would be great if you could tell me if there is any support to directly port pthread to pulp. Or all the pthread calls should be substituted with the corresponding rt_thread calls?

Thanks.

**Comment by haugoug** [comment]
There is no plan to have a pthread layer on pulp. We are planning to have freertos and zephyr for that but this is not ready yet.
The support for threads in pulp-os is still experimental, it is better to not use it for now. We normally use the cluster to do parallel computation, what do you want to do with multiple threads on the fabric controller ?
