### ISSUE TITLE
Bring the command line `gui=1` flag back to Makefiles (and fix `make conf`)

### ISSUE THREAD

**Issue by FrancescoConti** [pulp-platform/pulp-sdk#29]
Currently, it looks like the only way to run an RTL simulation with GUI involves first properly configuring the JSON configuration file with `make conf gui=1`, and then run as usual the application. It appears that at least in some cases `make conf gui=0` is not enough to deactivate it.

In the past, it was possible to directly add the `gui=1` flag to the `make run` line on the fly, which I think was much faster and enabled case-by-case GUI simulation... Is it possible to bring back this feature?

**Comment by haugoug** [comment]
This is planned but I need to finish the new runner first. Until it is done you can actually do that with recent sdks:
make conf all run gui=1
And to deactivate it:
make conf all run
