### ISSUE TITLE
Error in building SDK

### ISSUE THREAD

**Issue by valenaUsi** [pulp-platform/pulp-sdk#3]
Hello everyone, 

I am following the instructions for the section "SDK build with independent dependencies build" but I got some errors and I would like to ask your help.

I do:
```
source configs/pulpissimo.sh
source configs/platform-rtl.sh
make all
```

and I get:

> git submodule update --init
plpbuild --p sdk checkout build --stdout
OrderedDict([('core', 'riscyv2-fpu')])
FATAL ERROR: Unknown core: riscyv2-fpu
Makefile:3: recipe for target 'all' failed
make: *** [all] Error  255

I change the file pulp-sdk/pulp-tools/bin/userconfig/top_new.py to accept the architecture riscyv2-fpu.

But then I get:

> git submodule update --init
> plpbuild --p sdk checkout build --stdout
> OrderedDict([('core', 'riscyv2-fpu')])
> 
> MODULE hal:hal command checkout
> HEAD is now at 452bf37... Few fixes for pulpissimo release (#1)
> 
> MODULE pulp-rules:pulp-rules command checkout
> HEAD is now at 53f3692... Initial commit
> 
> MODULE archi:archi command checkout
> HEAD is now at 717e081... Few fixes for pulpissimo release (#3)
> 
> MODULE pulp-rt:pulp-rt command checkout
> HEAD is now at fd5682f... Few fixes for pulpissimo release (#1)
> 
> MODULE runner:runner command checkout
> HEAD is now at a666d86... Now setting proper core in RTL platform for pulpissimo (#1)
> 
> sdk:pulp-tools:prepare: make header
> make[1]: Entering directory 'my_dir/pulp-sdk/pulp-tools'
> install -D bin/userconfig/top_new.py my_dir/pulp-sdk/pkg/sdk/dev/install/ws/bin/userconfig/top_new.py
> install -D bin/plpbuild my_dir/pulp-sdk/pkg/sdk/dev/install/ws/bin/plpbuild
> touch my_dir/pulp-sdk/pkg/sdk/dev/install/rules/tools.mk
> make[1]: Leaving directory 'my_dir/pulp-sdk/pulp-tools'
> Reached EOF with exit status 0
> 
> sdk:pulp-rules:prepare: make all
> make[1]: Entering directory 'my_dir/pulp-sdk/tools/pulp-rules'
> make[1]: Nothing to be done for 'all'.
> make[1]: Leaving directory 'my_dir/pulp-sdk/tools/pulp-rules'
> Reached EOF with exit status 0
> 
> sdk:hal:prepare (user_config_file=my_dir/pulp-sdk/configs/json/pulpissimo.json): make header
> make[1]: Entering directory 'my_dir/pulp-sdk/runtime/hal'
> plpflags gen  --output-dir=my_dir/pulp-sdk/runtime/hal/build/user_config_file..my_dir.pulp-sdk.configs.json.pulpissimo.json --makefile=my_dir/pulp-sdk/runtime/hal/build/user_config_file..my_dir.pulp-sdk.configs.json.pulpissimo.json/config.mk    --out-config=my_dir/pulp-sdk/runtime/hal/build/user_config_file..my_dir.pulp-sdk.configs.json.pulpissimo.json/config.json
> OrderedDict([('core', 'riscyv2-fpu')])
> make[1]: *** No rule to make target 'my_dir/pulp-sdk/pkg/sdk/dev/install/include/OrderedDict([('core',)', needed by 'header'.  Stop.
> make[1]: Leaving directory 'my_dir/pulp-sdk/runtime/hal'
> Reached EOF with exit status 2
> Makefile:3: recipe for target 'all' failed
> make: *** [all] Error 255

In my setup the folder "my_dir/pulp-sdk/pkg/sdk/dev/install/include/" does not exist (my_dir is an abbreviation of my real path). Should I create this folder? how?

Thanks in advance for any help!

**Comment by haugoug** [comment]
It seems you have some local modifications which prints a python dictionary and disturbs the build process.
Anyway, I've pushed a new version in the master branch with some fixes, you should better remove your local folder and redo it with the new version. Let me know if you still have the issue.

**Comment by valenaUsi** [comment]
The error is solved in the new version!
