### ISSUE TITLE
pulp-sdk build error

### ISSUE THREAD

**Issue by speedzheng** [pulp-platform/pulp-sdk#30]
Hi,
I am going to build pulp SDK and choose pulp.sh but met this error:
source configs/pulp.sh
source configs/platform-rtl.sh
make all

.....
pulp/pulp-sdk/pulp-riscv-gnu-toolchain/riscv/bin/riscv32-unknown-elf-gcc  -march=rv32imcxpulpv2 -D__riscv__ -D__RT_USE_IO=1 -Os -g -fno-jump-tables -Werror -fno-tree-loop-distribute-patterns  -Wextra -Wall -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wundef -fdata-sections -ffunction-sections -I/home/speedzheng/pulp/pulp-sdk/pkg/sdk/dev/install/include/io -I/home/speedzheng/pulp/pulp-sdk/pkg/sdk/dev/install/include -include /home/speedzheng/pulp/pulp-sdk/build/sdk/pulp-rt/pulp/cl_config.h    -MMD -MP -c kernel/sync_mc.c -o /home/speedzheng/pulp/pulp-sdk/build/sdk/pulp-rt/pulp/rt/cl/kernel/sync_mc.o
In file included from /home/speedzheng/pulp/pulp-sdk/pkg/sdk/dev/install/include/rt/rt_api.h:57:0,
                 from kernel/sync_mc.c:21:
/home/speedzheng/pulp/pulp-sdk/pkg/sdk/dev/install/include/rt/rt_perf.h: In function 'rt_perf_cl_reset':
/home/speedzheng/pulp/pulp-sdk/pkg/sdk/dev/install/include/rt/rt_perf.h:217:19: error: implicit declaration of function 'hal_timer_cl_addr'; did you mean 'hal_timer_fc_addr'? [-Werror=implicit-function-declaration]
   hal_timer_reset(hal_timer_cl_addr(0, 0));
                   ^~~~~~~~~~~~~~~~~
                   hal_timer_fc_addr
cc1: all warnings being treated as errors

Thanks!

**Comment by alessandrocapotondi** [comment]
Dear @speedzheng,
I confirm your error. It is a regression and we are working on it.

Thanks for the support!

**Comment by alessandrocapotondi** [comment]
Dear @speedzheng,
      you can workaround the problem using fetching the `intergration` branch.

We will let you know when `master` branch will be fixed.

Thanks

**Comment by speedzheng** [comment]
it works. I have passed the build. Thanks!
