### ISSUE TITLE
build fail due to password

### ISSUE THREAD

**Issue by speedzheng** [pulp-platform/pulp-sdk#31]
Hi, when build sdk for hero_zc706.sh, it asks for the password, is it expected? Thanks!

The authenticity of host 'iis-git.ee.ethz.ch (129.132.2.24)' can't be established.
ECDSA key fingerprint is SHA256:jI6MDtrI7TVLgVlEPvDwfcNhbwW61ugYg8jo74W51Do.

**Comment by alessandrocapotondi** [comment]
Hi @speedzheng,
     `config/hero_zc706.sh` is not yet fully public for release. We are working on that and it will be released as soon as it will stable.

best regrads,
Alessandro
