### ISSUE TITLE
plpbuild update versions remove unintentionally other modules

### ISSUE THREAD

**Issue by alessandrocapotondi** [pulp-platform/pulp-sdk#33]
When `plpbuild --m <module> update versions` is execute some modules are removed unintentionally from `versions.cfg`:

-  'auto-tiler': '609c5dca5ffee400c0cb235e699786b321b6eddf',
-  'autotiler_examples': '99aea018af8ca5268219d0cc934800fa7dd8d916',

**Comment by haugoug** [comment]
Yes indeed I need to fix it

**Comment by haugoug** [comment]
This has been fixed in branch integration
