### ISSUE TITLE
make clean does not fully clean the build environment

### ISSUE THREAD

**Issue by FrancescoConti** [pulp-platform/pulp-sdk#35]
Since `make clean` does not really remove the build environment, it often happens that "cleaning" is not sufficient. For example, moving from old tests starting directly from the cluster (using `pulp.mk` and the env variable `PULP_APP_SRCS`) to newer tests starting from the fabric controller (using `pulp_rt.mk` and the env variable `PULP_APP_FC_SRCS`) will exhibit this behavior, stubbornly continuing to execute on the cluster after cleaning.

In this cases, removing the `build` directory is sufficient to work-around the problem. Nevertheless, I would suggest that `make clean` removes the environment by default.

**Comment by haugoug** [comment]
It is on purpose, the clean target is only removing files created during the build so that the files generated during the configuration are not lost. If you want to remove everything including generated files I can introduce a new target like "make distclean" ?
