### ISSUE TITLE
Getting/setting frequency does not work properly in SDK 2018.07.03

### ISSUE THREAD

**Issue by FrancescoConti** [pulp-platform/pulp-sdk#36]
In the 2018.07.03 SDK release, it appears that the `pulp-rt` functions to set the frequency for the fabric controller and clusters domain are broken.

Specifically, it appears that `rt_freq_get` always returns 0 instead of the current frequency, whereas `rt_freq_set` always returns -1 indicating a failure in changing the frequency.

**Comment by haugoug** [comment]
This has been fixed recently and the fix is available in the latest tag
