### ISSUE TITLE
calling rt_spim_open multiple times returns error

### ISSUE THREAD

**Issue by mrusci** [pulp-platform/pulp-sdk#38]
Tested on the GAP board, when using SPI1 to connect to two separate devices (hence using CS0 and CS1). When calling  `rt_spim_t *second_handler= rt_spim_open(NULL, &second_spim_conf, NULL)` once the first one was already opened,  the program returns error. 

Workaround:
```
void rt_spim_close(rt_spim_t *handle, rt_event_t *event)
{
  int channel = (handle->channel) >> 1 ;
  rt_spim_t *spim = &__rt_spim[__rt_spim_id(channel)];
  spim->open_count-- ;
}
```

**Comment by haugoug** [comment]
The API allows several devices to be opened at the same time on the same interface but the implementation is wrong it is using a single static structure while it should be allocated dynamically, I will fix it.

**Comment by haugoug** [comment]
This has been fixed and will be available in the next tag
