### ISSUE TITLE
Problem with ./update-sw-new in Mr.Wolf RTL platform

### ISSUE THREAD

**Issue by daviderossi1982** [pulp-platform/pulp-sdk#39]
Mr. Wolf RTL platform works only with the old "pulp_pipeline". When trying to get the new sdk using ./updated-sw-new i get the following:

Cloning into 'pulp-sdk'...
X11 forwarding request failed on channel 0
remote: Counting objects: 2023, done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 2023 (delta 33), reused 35 (delta 16), pack-reused 1971
Receiving objects: 100% (2023/2023), 372.22 KiB | 1.17 MiB/s, done.
Resolving deltas: 100% (1289/1289), done.
Branch 'integration' set up to track remote branch 'integration' from 'origin'.
Switched to a new branch 'integration'
Configuring Pulp project at /usr/scratch/larain5/drossi/wolf/pulp-sdk
git submodule update --init
Submodule 'json-tools' (https://github.com/pulp-platform/json-tools.git) registered for path 'json-tools'
Submodule 'pulp-configs' (https://github.com/pulp-platform/pulp-configs.git) registered for path 'pulp-configs'
Submodule 'pulp-tools' (https://github.com/pulp-platform/pulp-tools.git) registered for path 'pulp-tools'
Cloning into '/usr/scratch/larain5/drossi/wolf/pulp-sdk/json-tools'...
Cloning into '/usr/scratch/larain5/drossi/wolf/pulp-sdk/pulp-configs'...
Cloning into '/usr/scratch/larain5/drossi/wolf/pulp-sdk/pulp-tools'...
Submodule path 'json-tools': checked out 'd07a88d2fed9eb454feb0c799b303b3cfb237008'
Submodule path 'pulp-configs': checked out '779b25b024acf6f18f9bb6302c2f00432c89947c'
Submodule path 'pulp-tools': checked out '69e2f2c3f7d11b0485ed5781dcd49557f7156328'
**FATAL ERROR: name 'wolfe_name' is not defined**

**Comment by haugoug** [comment]
Wolfe tape-out was done with pulp_pipeline so only this one is maintained with the RTL flow. You can still use pulp-sdk on wolfe but you have to switch to the SDK flow for compiling the platform and this is then using another branch. Do you want to try it ?

**Comment by daviderossi1982** [comment]
Yes, please....it could be helpful for me to provide feedbacks to the developers in case of problems. Could you provide me detailed instructions?
