### ISSUE TITLE
Driver SPIM receive - problem with CS

### ISSUE THREAD

**Issue by tommasopolonelli** [pulp-platform/pulp-sdk#40]
I may have found an important bug in spim_receive. 
With the following code:
![image](https://user-images.githubusercontent.com/6155948/43895252-ec33f210-9bd4-11e8-8b29-674cefffcb92.png)
I would expect that the CS stays low after the first function call, as described in :
![image](https://user-images.githubusercontent.com/6155948/43895270-01d79504-9bd5-11e8-8a4d-38ea5200f7bf.png)
Indeed, the signal generated is the following (yellow: CLK, blue: CS):
![image](https://user-images.githubusercontent.com/6155948/43895289-1099e312-9bd5-11e8-9c06-f382e75068cc.png)

**Comment by tommasopolonelli** [comment]
A simple fix can be used to solve the problem:

edit this file: runtime/pulp-rt/drivers/spim/spim-v2.c

in function __rt_spim_receive replace the line:
`rt_periph_dual_copy(copy, handle->channel, (unsigned int)cmd, 4*4, (int)data, (len+7)>>3, 2<<1, call_event);`
with
`rt_periph_dual_copy(copy, handle->channel, (unsigned int)cmd, cs_mode == RT_SPIM_CS_AUTO ? 4*4 : 3*4, (int)data, (len+7)>>3, 2<<1, call_event);`

Then recompile with this command:
`plpbuild --m pulp-rt build --stdout`

**Comment by haugoug** [comment]
This has been pushed and will be in the next tag.
