### ISSUE TITLE
UPDATE SDK pulp error example

### ISSUE THREAD

**Issue by lfernand4** [pulp-platform/pulp-sdk#49]
Hi,
I have build the most recent patch from the SDK.
I execute "make all" without error. 
If I execute a program with pulpissimo I have no error.
And if i execute a code with pulp I have the following error : 
![image](https://user-images.githubusercontent.com/36438648/44401576-6331af00-a54f-11e8-8366-afd1bba18229.png)
Thank you!

**Comment by lfernand4** [comment]
I rebuild all the SDK and the pulp folder, and now i have the following error : 
![image](https://user-images.githubusercontent.com/36438648/44448514-c5d88880-a5eb-11e8-9e42-213874079864.png)

**Comment by haugoug** [comment]
Does it work now ?

**Comment by lfernand4** [comment]
Yes
