### ISSUE TITLE
Build error with newer gcc versions

### ISSUE THREAD

**Issue by magseet** [pulp-platform/pulp-sdk#74]
Trying to build the SDK on Ubuntu 18.10, using g++-8, the "make all" command fails (both on master and integration branches). I suggest to include (in the Readme) the procedure to switch to older gcc versions (before fixing the problem), as explained in this thread: 
https://askubuntu.com/questions/26498/how-to-choose-the-default-gcc-and-g-version

g++-7 works on some older branches, while g++-5 works on the master branch.

**Comment by haugoug** [comment]
Thanks a lot, I've put a note in the README
