### ISSUE TITLE
make error “cc1: error: requested ABI requires -march to subsume the 'D' extension”

### ISSUE THREAD

**Issue by tangshibin** [pulp-platform/pulp-sdk#76]
The toolchain is compiled with following instructions:
./configure --prefix=/opt/riscv32 --with-arch=rv32gc --with-abi=ilp32d
export PATH=$PATH:/opt/riscv32/bin
make -j4

But pulp-sdk make with errors.
My gcc version is gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11) ;

**Comment by haugoug** [comment]
Which error do you get ?
