### ISSUE TITLE
Minimum doxygen requirement of pulp-rt.dxy

### ISSUE THREAD

**Issue by holysml** [pulp-platform/pulp-sdk#9]
Hi, sdk team :

There is error msg of sdk building progress on pulp-rt.dxy :

cd pulp-rt && doxygen pulp-rt.dxy                                                                           
Warning: ignoring unsupported tag `PROJECT_BRIEF          =' at line 47, file pulp-rt.dxy                   
Warning: ignoring unsupported tag `PROJECT_LOGO           =' at line 54, file pulp-rt.dxy                   
Warning: ignoring unsupported tag `TCL_SUBST              =' at line 239, file pulp-rt.dxy                  
Warning: ignoring unsupported tag `MARKDOWN_SUPPORT       =' at line 293, file pulp-rt.dxy                  
Warning: ignoring unsupported tag `AUTOLINK_SUPPORT       =' at line 301, file pulp-rt.dxy                  
Warning: ignoring unsupported tag `INLINE_GROUPED_CLASSES =' at line 363, file pulp-rt.dxy                  
Warning: ignoring unsupported tag `INLINE_SIMPLE_STRUCTS  =' at line 373, file pulp-rt.dxy                  
Warning: ignoring unsupported tag `LOOKUP_CACHE_SIZE      =' at line 397, file pulp-rt.dxy                  
Warning: ignoring unsupported tag `EXTRACT_PACKAGE        =' at line 423, file pulp-rt.dxy                  
Warning: ignoring unsupported tag `SHOW_GROUPED_MEMB_INC  =' at line 516, file pulp-rt.dxy                  
Warning: ignoring unsupported tag `FORCE_LOCAL_INCLUDES   =' at line 522, file pulp-rt.dxy                  
Warning: ignoring unsupported tag `STRICT_PROTO_MATCHING  =' at line 582, file pulp-rt.dxy                  
Warning: ignoring unsupported tag `CITE_BIB_FILES         =' at line 681, file pulp-rt.dxy                  
Warning: ignoring unsupported tag `FILTER_SOURCE_PATTERNS =' at line 913, file pulp-rt.dxy                  
Warning: ignoring unsupported tag `USE_MDFILE_AS_MAINPAGE =' at line 920, file pulp-rt.dxy                  
Warning: ignoring unsupported tag `SOURCE_TOOLTIPS        =' at line 976, file pulp-rt.dxy                  
Warning: ignoring unsupported tag `CLANG_ASSISTED_PARSING =' at line 1017, file pulp-rt.dxy                 
Warning: ignoring unsupported tag `CLANG_OPTIONS          =' at line 1025, file pulp-rt.dxy                 
Warning: ignoring unsupported tag `HTML_EXTRA_STYLESHEET  =' at line 1128, file pulp-rt.dxy                 
Warning: ignoring unsupported tag `HTML_EXTRA_FILES       =' at line 1138, file pulp-rt.dxy                 
Warning: ignoring unsupported tag `HTML_COLORSTYLE_HUE    =' at line 1151, file pulp-rt.dxy                 
Warning: ignoring unsupported tag `HTML_COLORSTYLE_SAT    =' at line 1159, file pulp-rt.dxy                 
Warning: ignoring unsupported tag `HTML_COLORSTYLE_GAMMA  =' at line 1170, file pulp-rt.dxy                 
Warning: ignoring unsupported tag `HTML_INDEX_NUM_ENTRIES =' at line 1199, file pulp-rt.dxy                 
Warning: ignoring unsupported tag `DOCSET_PUBLISHER_ID    =' at line 1237, file pulp-rt.dxy                 
Warning: ignoring unsupported tag `DOCSET_PUBLISHER_NAME  =' at line 1243, file pulp-rt.dxy                 
Warning: ignoring unsupported tag `GENERATE_ECLIPSEHELP   =' at line 1378, file pulp-rt.dxy                 
Warning: ignoring unsupported tag `ECLIPSE_DOC_ID         =' at line 1386, file pulp-rt.dxy                 
Warning: ignoring unsupported tag `EXT_LINKS_IN_WINDOW    =' at line 1438, file pulp-rt.dxy                 
Warning: ignoring unsupported tag `FORMULA_TRANSPARENT    =' at line 1458, file pulp-rt.dxy                 
Warning: ignoring unsupported tag `USE_MATHJAX            =' at line 1469, file pulp-rt.dxy
Warning: ignoring unsupported tag `MATHJAX_FORMAT         =' at line 1479, file pulp-rt.dxy
Warning: ignoring unsupported tag `MATHJAX_RELPATH        =' at line 1492, file pulp-rt.dxy
Warning: ignoring unsupported tag `MATHJAX_EXTENSIONS     =' at line 1499, file pulp-rt.dxy
Warning: ignoring unsupported tag `MATHJAX_CODEFILE       =' at line 1507, file pulp-rt.dxy
Warning: ignoring unsupported tag `SERVER_BASED_SEARCH    =' at line 1540, file pulp-rt.dxy
Warning: ignoring unsupported tag `EXTERNAL_SEARCH        =' at line 1556, file pulp-rt.dxy
Warning: ignoring unsupported tag `SEARCHENGINE_URL       =' at line 1567, file pulp-rt.dxy
Warning: ignoring unsupported tag `SEARCHDATA_FILE        =' at line 1575, file pulp-rt.dxy
Warning: ignoring unsupported tag `EXTERNAL_SEARCH_ID     =' at line 1583, file pulp-rt.dxy
Warning: ignoring unsupported tag `EXTRA_SEARCH_MAPPINGS  =' at line 1593, file pulp-rt.dxy
Warning: ignoring unsupported tag `LATEX_FOOTER           =' at line 1679, file pulp-rt.dxy
Warning: ignoring unsupported tag `LATEX_EXTRA_FILES      =' at line 1687, file pulp-rt.dxy
Warning: ignoring unsupported tag `LATEX_BIB_STYLE        =' at line 1738, file pulp-rt.dxy
Warning: ignoring unsupported tag `GENERATE_DOCBOOK       =' at line 1868, file pulp-rt.dxy
Warning: ignoring unsupported tag `DOCBOOK_OUTPUT         =' at line 1876, file pulp-rt.dxy
Warning: ignoring unsupported tag `EXTERNAL_PAGES         =' at line 2049, file pulp-rt.dxy
Warning: ignoring unsupported tag `DIA_PATH               =' at line 2084, file pulp-rt.dxy
Warning: ignoring unsupported tag `DOT_NUM_THREADS        =' at line 2109, file pulp-rt.dxy
Warning: ignoring unsupported tag `UML_LIMIT_NUM_FIELDS   =' at line 2178, file pulp-rt.dxy
Warning: ignoring unsupported tag `INTERACTIVE_SVG        =' at line 2265, file pulp-rt.dxy
Warning: ignoring unsupported tag `MSCFILE_DIRS           =' at line 2284, file pulp-rt.dxy
Warning: ignoring unsupported tag `DIAFILE_DIRS           =' at line 2290, file pulp-rt.dxy
Warning: argument `0' for option ENUM_VALUES_PER_LINE is not a valid number in the range [1..20]!
Using the default: 4!
Warning: the type '(null)' is not supported for the entry tag within a navindex! Check your layout file!
Warning: the type '(null)' is not supported for the entry tag within a navindex! Check your layout file!
**/bin/sh: line 1: 13934 Segmentation fault      (core dumped) doxygen pulp-rt.dxy**
make[2]: *** [all] Error 139
make[2]: Leaving directory `/net/cola/data/sawu/proj/pulp-sdk_git/doc/dox'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/net/cola/data/sawu/proj/pulp-sdk_git/doc'
Reached EOF with exit status 2
make: *** [all] Error 255

I am using Redhat6 with doxygen **doxygen-1.6.1-6.el6.x86_64**; may I know what version in your environment?

Regards,
Samuel

**Comment by haugoug** [comment]
We use Centos7 and Ubuntu16
